# Model arguments
model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  # princeton-nlp/llama3-ultrafeedback-armorm: 1.0
  /home/lesong/codes/SimPO/datasets/llama3_3b_ultrafeedback/: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
beta: 10
gamma_beta_ratio: 0.3
do_eval: true
evaluation_strategy: steps
eval_steps: 10000
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: simpo-exps
trainer_type: simpo
learning_rate: 1.0e-6
log_level: info
logging_steps: 100
lr_scheduler_type: cosine
max_length: 3072
max_prompt_length: 2800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/llama-3-3b-instruct-simpo-v2
run_name: llama-3-3b-instruct-simpo-v2
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "steps"
save_steps: 1000000
eval_steps: 1000000
report_to:
- wandb
save_total_limit: 5
seed: 42
warmup_ratio: 0.1
